### ISSUE TITLE
Commvault Windows FS Package Installation - SDKException Response 101 

### ISSUE THREAD

**Issue by tobywfield** [CommvaultEngg/ansible#12]
Hi, my company is attempting to deploy a new Windows agent via Commvault Ansible/Cvpysdk and we are running into this issue. We are on SP20 and are using the latest ansible/cvpysdk code. It logs into the commcell successfully, but immediately fails when attempting to install the software to the client. We can add the client without issue through the webconsole gui, but not with ansible.
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_commvault_payload_qmxsa6mm/ansible_commvault_payload.zip/ansible/modules/commvault.py", line 301, in <module>
  File "/tmp/ansible_commvault_payload_qmxsa6mm/ansible_commvault_payload.zip/ansible/modules/commvault.py", line 288, in main
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/cvpysdk/commcell.py", line 2120, in install_software
    storage_policy_name=storage_policy_name)
  File "/usr/local/lib/python3.6/site-packages/cvpysdk/deployment/install.py", line 581, in install_software
    raise SDKException('Response', '101')
cvpysdk.exception.SDKException: Response was not success
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_commvault_payload_qmxsa6mm/ansible_commvault_payload.zip/ansible/modules/commvault.py\", line 301, in <module>\n  File \"/tmp/ansible_commvault_payload_qmxsa6mm/ansible_commvault_payload.zip/ansible/modules/commvault.py\", line 288, in main\n  File \"<string>\", line 1, in <module>\n  File \"/usr/local/lib/python3.6/site-packages/cvpysdk/commcell.py\", line 2120, in install_software\n    storage_policy_name=storage_policy_name)\n  File \"/usr/local/lib/python3.6/site-packages/cvpysdk/deployment/install.py\", line 581, in install_software\n    raise SDKException('Response', '101')\ncvpysdk.exception.SDKException: Response was not success\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by cvltrevathys** [comment]
Hi toby,

Please contact commvault support and raise a ticket with them

**Comment by spakhare** [comment]
Passing base64 encoded password fixed this issue.
